# 🌍 Análisis de Emisiones de CO₂ (1750–2021)
### Dataset: Global Carbon Project – GCB2022v27_MtCO2_flat.csv

El presente notebook analiza la evolución histórica de las emisiones globales de dióxido de carbono (CO₂) por tipo de fuente y por país, a partir de los datos del **Global Carbon Project**.

El **Global Carbon Project (GCP)** es una iniciativa científica internacional dedicada a **cuantificar las emisiones y sumideros de carbono** a nivel global, con el fin de **apoyar políticas climáticas basadas en evidencia**.

🔗 **Fuente oficial del dataset:** [Global Carbon Project – CO₂ Emissions Dataset](https://www.globalcarbonproject.org/carbonbudget)

El objetivo es ofrecer una visión integral sobre la evolución de las emisiones globales de CO₂, sus principales fuentes y las diferencias entre países a lo largo del tiempo.

---

## 📑 Descripción del dataset

El dataset contiene las emisiones anuales de CO₂ (en **millones de toneladas – MtCO₂**) desagregadas por país y por fuente de emisión.  

Las principales columnas son:

- **Country** → País emisor.  
- **Year** → Año del registro.  
- **Total** → Emisiones totales de CO₂ del país en ese año.  
- **Coal** → Emisiones derivadas del uso de carbón.  
- **Oil** → Emisiones derivadas del uso de petróleo.  
- **Gas** → Emisiones derivadas del uso de gas natural.  
- **Cement** → Emisiones asociadas a la producción de cemento.  
- **Flaring** → Emisiones por quema de gases residuales en la extracción de petróleo y gas.

> ℹ️ Los datos cubren más de 150 países y abarcan un periodo extenso (1750–2021).  
> En este notebook se trabaja principalmente desde **1925 en adelante**, para centrarse en la era industrial moderna y contar con registros más consistentes.

---

## 🎯 Objetivos del análisis

1. Realizar un **análisis exploratorio de datos (EDA)** para comprender la evolución global de las emisiones.  
2. Identificar a los **principales emisores históricos** y su evolución a lo largo del tiempo.  
3. Comparar **fuentes de emisión** (carbón, petróleo, gas, etc.) y cómo ha cambiado su peso relativo.  
4. Analizar casos específicos de interés, como **China** y **Estados Unidos**, los dos mayores emisores actuales.  
5. Explorar visualizaciones avanzadas como:  
   - Series de tiempo globales.  
   - Gráficos por década.  
   - Correlaciones entre fuentes.  
   - Gráficos apilados para mostrar la transición energética.

---
## 🗂️ Contenido del notebook
1. Descripción del dataset  
2. Carga y exploración inicial  
3. Tratamiento de datos  
4. Análisis exploratorio  
5. Visualizaciones globales  
6. Análisis por país (China vs EE.UU.)  
7. Conclusiones

---
A continuación, se realiza la **carga y exploración inicial del dataset** para conocer su estructura y principales características.

In [39]:
#librerías necesarias
import pandas as pd
import numpy as np
# Visualización
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [40]:
# Configuración de gráficos
%matplotlib inline
sns.set(style="whitegrid")

In [41]:
# Asegúrate de que el CSV esté en el mismo directorio que tu notebook
df = pd.read_csv("GCB2022v27_MtCO2_flat.csv")

# Visualizamos las primeras filas
df.head()

,Country,ISO 3166-1 alpha-3,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
0,Afghanistan,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
df.tail()

,Country,ISO 3166-1 alpha-3,Year,Total,Coal,Oil,Gas,Cement,Flaring,Other,Per Capita
63099,Global,WLD,2017,36096.739276,14506.973805,12242.627935,7144.928128,1507.923185,391.992176,302.294047,4.749682
63100,Global,WLD,2018,36826.506600,14746.830688,12266.016285,7529.846784,1569.218392,412.115746,302.478706,4.792753
63101,Global,WLD,2019,37082.558969,14725.978025,12345.653374,7647.528220,1617.506786,439.253991,306.638573,4.775633
63102,Global,WLD,2020,35264.085734,14174.564010,11191.808551,7556.290283,1637.537532,407.583673,296.301685,4.497423
63103,Global,WLD,2021,37123.850352,14979.598083,11837.159116,7921.829472,1672.592372,416.525563,296.145746,4.693699

In [43]:
df.columns

Index(['Country', 'ISO 3166-1 alpha-3', 'Year', 'Total', 'Coal', 'Oil', 'Gas',
       'Cement', 'Flaring', 'Other', 'Per Capita'],
      dtype='object')

In [44]:
# Tamaño y estructura
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")

df.info()

Filas: 63104, Columnas: 11
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63104 entries, 0 to 63103
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             63104 non-null  object
 1   ISO 3166-1 alpha-3  61472 non-null  object
 2   Year                63104 non-null  int64
 3   Total               62904 non-null  float64
 4   Coal                21744 non-null  float64
 5   Oil                 21717 non-null  float64
 6   Gas                 21618 non-null  float64
 7   Cement              20814 non-null  float64
 8   Flaring             21550 non-null  float64
 9   Other               1620 non-null   float64
 10  Per Capita          18974 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 5.3+ MB

In [45]:
df.shape
print(df.shape) 
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")

(63104, 11)
Filas: 63104, Columnas: 11

In [46]:
# datos nulos 
df.isnull().sum()

Country                   0
ISO 3166-1 alpha-3     1632
Year                      0
Total                   200
Coal                  41360
Oil                   41387
Gas                   41486
Cement                42290
Flaring               41554
Other                 61484
Per Capita            44130
dtype: int64

## 🧹 Tratamiento de Datos

In [47]:
# 1. Recalcular 'Total' cuando está nulo, sumando fuentes disponibles
df["Total"] = df["Total"].fillna(
    df[["Coal", "Oil", "Gas", "Cement", "Flaring", "Other"]].sum(axis=1)
)

# 2. Imputar columnas de fuentes con la media por país (solo si hay valores disponibles)
for col in ["Coal", "Oil", "Gas", "Cement", "Flaring"]:
    df[col] = df.groupby("Country")[col].transform(lambda x: x.fillna(x.mean()))

# 3. Eliminar columnas con más del 90% de nulos (poca utilidad para análisis general)
df.drop(columns=["Other", "Per Capita"], inplace=True)

In [48]:
# 4. Confirmar que la limpieza se aplicó correctamente
print("Nulos restantes por columna:")
print(df.isnull().sum())

Nulos restantes por columna:
Country                  0
ISO 3166-1 alpha-3    1632
Year                     0
Total                    0
Coal                   272
Oil                      0
Gas                    272
Cement                 272
Flaring                272
dtype: int64

In [49]:
# Ver países con datos faltantes en esas columnas
nulos_df = df[df[["Coal", "Gas", "Cement", "Flaring"]].isnull().any(axis=1)]
print(nulos_df["Country"].value_counts())

Country
International Transport    272
Name: count, dtype: int64

In [50]:
# Eliminar filas con cualquier nulo restante en columnas clave
df.dropna(subset=["Coal", "Gas", "Cement", "Flaring"], inplace=True)

# Verificación final
print("Nulos restantes por columna:")
print(df.isnull().sum())

Nulos restantes por columna:
Country                  0
ISO 3166-1 alpha-3    1632
Year                     0
Total                    0
Coal                     0
Oil                      0
Gas                      0
Cement                   0
Flaring                  0
dtype: int64

In [51]:
# Eliminar columna con muchos nulos que no es esencial por ahora
df.drop(columns=["ISO 3166-1 alpha-3"], inplace=True)

# Verificar nulos restantes en el DataFrame
print("Verificación final - Nulos por columna:")
print(df.isnull().sum())
print(f"\nTamaño final del dataset: {df.shape[0]} filas × {df.shape[1]} columnas")

Verificación final - Nulos por columna:
Country    0
Year       0
Total      0
Coal       0
Oil        0
Gas        0
Cement     0
Flaring    0
dtype: int64

Tamaño final del dataset: 62832 filas × 8 columnas

## 📊 Análisis Exploratorio de Datos (EDA)

In [52]:
df.head()

       Country  Year  Total      Coal       Oil       Gas    Cement  Flaring
0  Afghanistan  1750    0.0  0.790089  1.802428  0.277625  0.034475  0.08159
1  Afghanistan  1751    0.0  0.790089  1.802428  0.277625  0.034475  0.08159
2  Afghanistan  1752    0.0  0.790089  1.802428  0.277625  0.034475  0.08159
3  Afghanistan  1753    0.0  0.790089  1.802428  0.277625  0.034475  0.08159
4  Afghanistan  1754    0.0  0.790089  1.802428  0.277625  0.034475  0.08159

In [53]:
# nuevas columnas
df.columns

Index(['Country', 'Year', 'Total', 'Coal', 'Oil', 'Gas', 'Cement', 'Flaring'], dtype='object')

In [54]:
# info estadística
df.describe()

,Year,Total,Coal,Oil,Gas,Cement,Flaring
count,62832.000000,62832.000000,62832.000000,62832.000000,62832.000000,62832.000000,62832.000000
mean,1885.500000,54.602709,34.027741,33.267584,14.745335,3.404792,1.880288
std,78.519731,825.038274,363.940892,341.132102,168.026622,33.592309,17.560484
min,1750.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1817.750000,0.000000,0.000000,0.211860,0.000000,0.000000,0.000000
50%,1885.500000,0.000000,0.045390,1.338247,0.000000,0.106880,0.000000
75%,1953.250000,0.538608,1.916048,6.170420,1.196723,0.735370,0.020281
max,2021.000000,37123.850352,15051.512770,12345.653374,7921.829472,1672.592372,439.253991

In [55]:
# nuevo tamaño y estructura
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62832 entries, 0 to 63103
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  62832 non-null  object
 1   Year     62832 non-null  int64
 2   Total    62832 non-null  float64
 3   Coal     62832 non-null  float64
 4   Oil      62832 non-null  float64
 5   Gas      62832 non-null  float64
 6   Cement   62832 non-null  float64
 7   Flaring  62832 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 4.3+ MB

## 🌎 Visualizaciones Globales (1750–2021)

**Emisiones globales de CO₂ a través del tiempo (1750 - 2021)**

In [56]:
#Evolución global de emisiones de CO₂ a lo largo del tiempo
import plotly.express as px

global_by_year = df.groupby("Year")["Total"].sum().reset_index()

fig = px.line(global_by_year, x="Year", y="Total", title="🌍 Emisiones globales de CO₂ por año", labels={"Total": "Emisiones (MtCO₂)"})
fig.show()

**Interpretación: Emisiones globales de CO₂ por año (1750–2021)**

- **1750–1850:** Las emisiones se mantienen en niveles muy bajos y casi imperceptibles, lo que refleja una economía basada en procesos productivos pre-industriales y con registros escasos en ese periodo.

- **1850–1900:** Se inicia un crecimiento visible de emisiones, asociado a la Revolución Industrial, la expansión del uso del carbón y el aumento de la producción fabril.

- **1900–1950:** Se observa un crecimiento sostenido con algunas caídas puntuales en 1932 (Gran Depresión) y 1945 (Segunda Guerra Mundial), pero con tendencia clara al alza durante la primera mitad del siglo XX.

- **1950 en adelante:** Las emisiones aumentan de manera casi exponencial, impulsadas por la industrialización global, el auge del petróleo y la expansión del consumo energético. Solo se aprecian leves descensos en años críticos como 1983 (crisis económica) y 2020 (COVID-19).

➡️ En conjunto, este gráfico muestra la aceleración histórica del cambio climático: el crecimiento de las emisiones de CO₂ está directamente vinculado a la industrialización y al modelo de desarrollo económico global.

---

**Top 10 países con mayores emisiones totales**

In [57]:
top_emitters = df.groupby("Country")["Total"].sum().sort_values(ascending=False).head(10)

fig = px.bar(top_emitters, x=top_emitters.index, y=top_emitters.values,
             title="🔝 Top 10 países emisores de CO₂ (acumulado)",
             labels={"x": "País", "y": "Emisiones (MtCO₂)"})
fig.show()

**Comparar fuentes de emisiones (Coal, Oil, Gas, Cement, Flaring)**

In [58]:
fuentes = ["Coal", "Oil", "Gas", "Cement", "Flaring"]
global_fuentes = df[fuentes].sum().sort_values(ascending=False)

fig = px.pie(names=global_fuentes.index, values=global_fuentes.values,
             title="🧱 Distribución global de emisiones por fuente 1750-2021")
fig.show()

**Evolución por tipo de fuente a través del tiempo (1750-2021)**

In [59]:
emisiones_fuentes = df.groupby("Year")[fuentes].sum().reset_index()

fig = px.line(emisiones_fuentes, x="Year", y=fuentes, title="📊 Evolución de emisiones por tipo de fuente")
fig.show()

### Análisis del gráfico

- **1750–1855:**  
El gráfico muestra que, en este periodo inicial, las emisiones asociadas al **petróleo (Oil)** aparecen levemente por encima del **carbón (Coal)** y del **gas (Gas)**. Sin embargo, este comportamiento refleja más una **limitación en los registros históricos** que una realidad productiva, ya que el uso masivo de petróleo no se consolidó sino hasta mediados del siglo XIX.  
Históricamente, el **carbón** fue la primera fuente energética con impacto global en las emisiones, especialmente a partir de la Revolución Industrial. En este tramo, las emisiones totales permanecen casi imperceptibles, reflejando una economía preindustrial y una muy baja intensidad energética.

- **1855–1950:**  
El **carbón (Coal)** adquiere un rol predominante, con un aumento sostenido y marcado en su pendiente, consolidándose como la principal fuente de emisiones durante este periodo.  
En contraste, las emisiones de **petróleo (Oil)** crecen a un ritmo más moderado, al igual que las de **gas (Gas)**, que mantienen una tendencia estable.  
Las fuentes **Cement** y **Flaring** continúan con niveles muy bajos y prácticamente constantes.

- **1950–2021:**  
A partir de mediados del siglo XX, se observa una **aceleración significativa** de las emisiones provenientes del **carbón**, cuya curva adopta una forma casi exponencial, seguida por un incremento notable del **petróleo (Oil)**.  
Sin embargo, desde el año 2000, el petróleo muestra una **leve desaceleración**, mientras el carbón se consolida como la fuente más contaminante a nivel global.   El **gas (Gas)** mantiene un crecimiento sostenido, aunque sin alcanzar los niveles de las dos fuentes principales. Finalmente, **Cement** y **Flaring** registran un aumento moderado desde los años 80, pero continúan representando una fracción menor dentro del total global de emisiones.

------------------------------------------------------------------------------------------------------------------------------

## 📈 Analisis desde 1925 hasta 2021

**Para tal efecto crearemos un nuevo DataFrame desde 1925**

In [60]:
# Crear nuevo DataFrame solo con datos desde 1925 en adelante
df_1925 = df[df["Year"] >= 1925].copy()

# Verificamos que se haya hecho bien
print(f"Filas totales desde 1925: {df_1925.shape[0]}")
print(df_1925["Year"].min(), "→", df_1925["Year"].max())

Filas totales desde 1925: 22407
1925 → 2021

In [61]:
df_1925.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22407 entries, 175 to 63103
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  22407 non-null  object
 1   Year     22407 non-null  int64
 2   Total    22407 non-null  float64
 3   Coal     22407 non-null  float64
 4   Oil      22407 non-null  float64
 5   Gas      22407 non-null  float64
 6   Cement   22407 non-null  float64
 7   Flaring  22407 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.5+ MB

In [62]:
df_1925.describe()

,Year,Total,Coal,Oil,Gas,Cement,Flaring
count,22407.000000,22407.000000,22407.000000,22407.000000,22407.000000,22407.000000,22407.000000
mean,1973.000000,142.688892,62.053187,54.023722,22.840762,4.120715,2.092451
std,28.000625,1371.897974,580.628932,510.383253,243.308673,48.532981,18.550945
min,1925.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1949.000000,0.014656,0.000000,0.212512,0.000000,0.000000,0.000000
50%,1973.000000,1.342800,0.014603,1.410640,0.000000,0.051668,0.000000
75%,1997.000000,17.343841,2.748041,8.183720,0.691223,0.583460,0.000000
max,2021.000000,37123.850352,15051.512770,12345.653374,7921.829472,1672.592372,439.253991

### 📊 Visualizaciones Globales desde 1925

**Evolución global emisiones de CO₂ (1925-2021)**

In [63]:
# 🌍 Evolución global de emisiones de CO₂ desde 1925 hasta 2021

global_by_year = df_1925.groupby("Year")["Total"].sum().reset_index()

fig = px.line(global_by_year, 
              x="Year", 
              y="Total", 
              title="🌍 Emisiones globales de CO₂ desde 1925 hasta 2021",
              labels={"Total": "Emisiones globales (MtCO₂)", "Year": "Año"})

fig.update_traces(line_color="firebrick", line_width=3)
fig.show()

**Observación:**

- A contar de la década del 50, se puede ver claramente cómo la curva de emisiones global crece de forma casi exponencial.

**Diez países con mayores emisiones (1925-2021)**

In [64]:
# Diez países con mayores emisiones desde 1925
top_emitters2 = df_1925.groupby("Country")["Total"].sum().sort_values(ascending=False).head(10)

fig = px.bar(top_emitters2, x=top_emitters2.index, y=top_emitters2.values,
             title="🔝 Top 10 países emisores de CO₂ desde 1925(acumulado)",
             labels={"x": "País", "y": "Emisiones (MtCO₂)"})
fig.show()

**Interpretación gráfico Top 10 emisores acumulados desde 1925**

- Estados Unidos (379.924k MtCO₂) y China (248.79k MtCO₂) son, con diferencia, los mayores emisores históricos, lo que refleja tanto su desarrollo económico como su dependencia de los combustibles fósiles en distintos momentos de la historia.

- Rusia y Alemania también presentan emisiones muy relevantes, aunque en menor medida, producto de su industrialización temprana y uso intensivo de carbón y petróleo.

- Reino Unido, Canadá y Francia aparecen en el ranking, pero con cifras mucho más bajas, lo que refleja su peso histórico en emisiones pero con menor impacto acumulado frente a los dos líderes.

- En conjunto, estos diez países concentran la mayor parte de las emisiones globales de CO₂, lo que confirma que las políticas climáticas de un grupo reducido de economías son determinantes para el futuro de las emisiones a nivel global.

------------------------------------------------------------------------------------------------------------------------------

 **Distribución de emisiones por tipo de fuente (1925–2021)**

In [65]:
# Emisiones por tipo de fuente desde 1925 hasta 2021
emisiones_fuentes = df_1925.groupby("Year")[fuentes].sum().reset_index()

fig = px.line(emisiones_fuentes, x="Year", y=fuentes, title="📊 Evolución de emisiones por tipo de fuente desde 1925")
fig.show()

### 📈 Evolución de las emisiones por tipo de fuente (1925–2021)

El gráfico muestra la evolución diferenciada de las principales fuentes de emisiones de CO₂ desde 1925, destacando el predominio del **carbón**, el auge del **petróleo** y la expansión del **gas natural** en el siglo XX.

- **Carbón (Coal):**  
  Mantiene un crecimiento casi constante con breves caídas en 1932 (Gran Depresión) y 1945 (Segunda Guerra Mundial). Desde el año 2000 acelera su ritmo, alcanzando su punto máximo en torno a 2012 y estabilizándose luego en niveles muy altos, impulsado por el peso de **China** en el escenario global.

- **Petróleo (Oil):**  
  Exhibe una fuerte expansión entre 1950 y 1973, interrumpida por la **crisis del petróleo**. Posteriormente alterna periodos de recuperación y estancamiento, con una tendencia general al alza hasta 2020. Refleja la **dependencia del transporte y la industria** de los combustibles líquidos.

- **Gas:**  
  Su crecimiento se intensifica desde los años 50, consolidándose como **energía de transición** con un aumento sostenido y continuo hasta 2020.

- **Cement y Flaring:**  
  Ambas fuentes mantienen un **peso marginal** respecto de los combustibles fósiles. El cemento aumenta desde los 80, vinculado al auge de la construcción, mientras que el flaring permanece casi constante a lo largo del periodo.

🔹 **Conclusión general:**  
Entre 1925 y 2021, el carbón conserva el liderazgo en emisiones globales, seguido por el petróleo, mientras el gas gana relevancia como fuente intermedia. El patrón histórico refleja cómo las transiciones energéticas han sido **graduales y dependientes del desarrollo industrial**, sin una sustitución total de los combustibles fósiles.

------------------------------------------------------------------------------------------------------------------------------

**Distribución de emisiones por tipo de fuente (1925–2021)**

In [66]:
# Distribución de emisiones por tipo de fuente desde 1925
import plotly.express as px

# Lista de fuentes
fuentes = ["Coal", "Oil", "Gas", "Cement", "Flaring"]

# Agrupamos por año y sumamos emisiones por fuente
df_fuentes = df_1925.groupby("Year")[fuentes].sum().reset_index()

# Crear gráfico de áreas apiladas
fig = px.area(df_fuentes,
              x="Year",
              y=fuentes,
              title="🧮 Distribución de emisiones por tipo de fuente (1925–2021)",
              labels={"value": "Emisiones (MtCO₂)", "variable": "Fuente"},
              template="plotly_white")

fig.show()

**Interpretación: Distribución de emisiones por tipo de fuente (1925–2021)**

- Carbón (Coal) y Petróleo (Oil); dominan claramente las emisiones globales, marcando una diferencia notable respecto a las demás fuentes. El carbón se mantiene como la fuente más importante en casi todo el periodo analizado.

- Gas empieza a crecer significativamente a partir de la década de 1950, consolidándose como una fuente cada vez más relevante, aunque todavía menor en comparación con carbón y petróleo.

- Cement y Flaring tienen una contribución relativamente baja en el total. En particular: 
  - Cement presenta un incremento leve desde los años 80, ligado a la expansión de la construcción. 
  - Flaring mantiene una tendencia estable y con bajo impacto en todo el periodo.

En conjunto, este gráfico refleja que, pese a la diversificación energética, las emisiones históricas están concentradas principalmente en el uso de combustibles fósiles tradicionales.

------------------------------------------------------------------------------------------------------------------------------

**Distribución (%) de fuentes de emisiones de CO₂ (1925-2021)**

In [67]:
# Columnas de fuentes
fuentes = ["Coal", "Oil", "Gas", "Cement", "Flaring"]

# Agrupar por año sumando emisiones globales
df_fuentes = df_1925.groupby("Year")[fuentes + ["Total"]].sum().reset_index()

# Calcular proporciones (%)
for fuente in fuentes:
    df_fuentes[fuente + "_pct"] = df_fuentes[fuente] / df_fuentes["Total"] * 100

# Gráfico de áreas apiladas
fig = px.area(
    df_fuentes,
    x="Year",
    y=[f + "_pct" for f in fuentes],
    title="📊 Distribución (%) de fuentes de emisiones de CO₂ a lo largo del tiempo",
    labels={"value": "Proporción (%)", "variable": "Fuente", "Year": "Año"}
)

fig.update_layout(yaxis_title="Porcentaje (%)", legend_title="Fuente de emisión")
fig.show()

**Observaciones relevantes**:

- **1925–1940:**
El carbón (Coal) domina claramente la composición de emisiones, representando en promedio cerca del 80 % del total mundial. Muy por detrás se ubica el petróleo (Oil), con una participación que oscila entre 25 % y 30 %, mientras que las demás fuentes son marginales.

- **Décadas de 1940–1960:**
A partir de los años 40, el porcentaje de emisiones provenientes del carbón comienza a disminuir gradualmente, mientras que las de petróleo (Oil) y, en menor medida, gas (Gas) aumentan su participación. Las fuentes Cement y Flaring se mantienen prácticamente constantes y con peso muy bajo.

- **Décadas de 1960–2000:**
Hacia mediados de los 60, la proporción del carbón cae por debajo del 50 %, impulsada por el fuerte crecimiento del petróleo, que se convierte en la principal fuente de emisiones de CO₂ a nivel global, superando el 40% a mediados de los 70. El gas natural también gana relevancia, aunque en una magnitud menor.

- **Desde 2000 en adelante:**
A comienzos del siglo XXI, el carbón retoma el liderazgo en las emisiones de CO₂, superando nuevamente al petróleo en participación global. En tercer lugar se ubica el gas, que continúa aumentando sus emisiones, mientras que cement y flaring se mantienen a gran distancia, con contribuciones pequeñas pero en crecimiento sostenido.

----

**Emisiones globales de CO₂ por década**

In [68]:
# Crear columna de década
df_1925["Década"] = (df_1925["Year"] // 10) * 10

# Agrupar por década y sumar emisiones totales
emisiones_decadas = df_1925.groupby("Década")["Total"].sum().reset_index()

# Gráfico de barras
fig = px.bar(emisiones_decadas,
             x="Década",
             y="Total",
             title="📊 Emisiones globales de CO₂ por década",
             labels={"Total": "Emisiones (MtCO₂)"},
             text_auto=".2s")

fig.update_traces(marker_color="indianred")
fig.update_layout(xaxis_title="Década", yaxis_title="Emisiones (MtCO₂)")
fig.show()

## ⚖️ 🇨🇳 vs 🇺🇸 Comparación China – EE.UU. (1925–2021)

**Evolución de CO₂: China vs USA (1925–2021)**

In [69]:
#Evolución de emisiones de CO₂: China vs USA (1925–2021)

# Filtrar solo los dos países
df_comparacion = df_1925[df_1925["Country"].isin(["China", "USA"])]

# Agrupar por año y país, sumando emisiones totales
df_comparacion = df_comparacion.groupby(["Year", "Country"])["Total"].sum().reset_index()

# Gráfico de líneas
fig = px.line(df_comparacion,
              x="Year",
              y="Total",
              color="Country",
              title="📈 Emisiones de CO₂: China vs USA (1925–2021)",
              labels={"Total": "Emisiones (MtCO₂)", "Year": "Año"})

fig.show()

### China vs US Emisiones de CO₂ (1925–2021)

**1925–1950**

- Estados Unidos presenta emisiones muy superiores a China, con una línea ascendente.

- En este periodo China prácticamente no muestra crecimiento significativo.

- Se observa una leve caída de emisiones CO₂ durante los años 30 por parte de EE.UU., vinculada a la Gran Depresión.

**1950–2000**

- EE.UU. mantiene un claro predominio en emisiones.

- A mediados de los 50, China comienza un crecimiento progresivo de sus emisiones.

- Desde la década de 1970, la curva de China acelera su pendiente, marcando el inicio de un crecimiento más sostenido.

**2000 en adelante**

- China experimenta un crecimiento exponencial, mientras que EE.UU. entra en una fase de estabilización con ligera tendencia a la baja.

- El 2006 se produce el punto de convergencia: China supera por primera vez a EE.UU. en emisiones de CO₂.

- Desde entonces, China continúa aumentando (con excepciones puntuales como 2005), consolidándose como el mayor emisor global.

📌 **Conclusión**: 
- El gráfico refleja el **traspaso del liderazgo en emisiones**:  
**Estados Unidos** dominó el siglo XX como principal emisor, mientras que **China** asumió ese rol en el siglo XXI, impulsado por su acelerada industrialización y urbanización.  
- Este desplazamiento del liderazgo en emisiones no solo marca un cambio en la **geografía económica mundial**, sino también en los **desafíos de la gobernanza climática global**, donde el equilibrio entre desarrollo y sostenibilidad se vuelve cada vez más crucial.

------------------------------------------------------------------------------------------------------------------------------

**Comparación de emisiones por década (barras lado a lado)**

In [70]:
# Definir países a comparar
paises = ["China", "USA"]

# Crear columna de década
df_1925["Decada"] = (df_1925["Year"] // 10) * 10
# filtrar y agrupar
df_decada = df_1925[df_1925["Country"].isin(paises)].copy()
df_decada["Década"] = (df_decada["Year"] // 10) * 10
df_decada = df_decada.groupby(["Década", "Country"])["Total"].sum().reset_index()
# Gráfico de barras
fig = px.bar(df_decada, x="Década", y="Total", color="Country", barmode="group",
             title="📊 Emisiones totales por década: China vs USA",
             labels={"Total": "Emisiones (MtCO₂)"})

fig.show()

**Evolución de emisiones por fuente (líneas múltiples)**

In [71]:
# Filtrar países y fuentes
paises = ["China", "USA"]
fuentes = ["Coal", "Oil", "Gas", "Cement", "Flaring"]

df_fuentes = df_1925[df_1925["Country"].isin(paises)]

# Agrupar por país, año y fuente (forma larga)
df_long = df_fuentes.melt(id_vars=["Country", "Year"], value_vars=fuentes,
                          var_name="Fuente", value_name="Emisiones")

# Gráfico
fig = px.line(df_long, x="Year", y="Emisiones", color="Fuente", facet_col="Country",
              title="📈 Evolución de emisiones por fuente: China vs USA",
              labels={"Emisiones": "MtCO₂"})

fig.show()

🧩 Análisis del gráfico

- **China:**
A partir de 1950, las emisiones provenientes del carbón (Coal) comienzan a incrementarse de manera sostenida, con una pendiente claramente ascendente. Este crecimiento se vuelve casi exponencial desde el año 2000, coincidiendo con la expansión industrial y urbana del país.
En contraste, las demás fuentes (Oil, Gas, Cement, Flaring) presentan incrementos más moderados y graduales, siendo el petróleo (Oil) la segunda fuente más destacada desde la década de 1970, aunque sin superar los 2000 MtCO₂.

- **Estados Unidos:**
Las emisiones de carbón (Coal) muestran un comportamiento más irregular: fueron más elevadas que las de China hasta mediados de los años 80, pero desde 2008 presentan una clara tendencia a la baja, reflejando la sustitución del carbón por gas natural y energías más limpias.
El petróleo (Oil) mantiene niveles superiores a los de China durante todo el periodo, mientras que el gas (Gas) tiene un papel más destacado que en China, con valores que superan los 1000 MtCO₂ en la década de 1970, aunque sin sobrepasar los 2000 MtCO₂.
Las emisiones por Cement y Flaring se mantienen constantes y con escasa variación, reflejando su menor peso relativo en la matriz energética estadounidense.

----

## 🔍 Conclusiones Finales

El análisis de las emisiones de CO₂ entre 1925 y 2021 permite identificar tendencias históricas, cambios estructurales y patrones energéticos que explican la evolución del impacto humano sobre el clima global.

- **Evolución global**  
  - Las emisiones de CO₂ se mantuvieron prácticamente imperceptibles hasta mediados del siglo XIX.  
  - Con la **Revolución Industrial** (1850–1900) comenzó un crecimiento sostenido, especialmente por el uso del carbón.
  - A partir de 1950, las emisiones globales exhiben un crecimiento casi exponencial, con breves descensos asociados a crisis económicas o eventos globales (por ejemplo, 1973 y 2020).

- **Principales emisores históricos** 
  - EE.UU. y China se consolidan como los grandes dominadores en términos de emisiones acumuladas de CO₂. EE.UU. lideró durante más de un siglo debido a su temprana industrialización, alto consumo energético y expansión económica.

  - China asumió un papel protagónico en las últimas décadas (siglo XXI) con un crecimiento acelerado impulsado por su industrialización acelerada y su fuerte dependencia del carbón como fuente energética.

  - Europa tuvo un rol pionero en las emisiones históricas: 
    - Alemania y Reino Unido fueron actores clave durante las primeras etapas de la industrialización. Hoy, sin embargo, representan una proporción mucho menor en el contexto global, en parte por transiciones energéticas y políticas de reducción de carbono.
    - Francia destaca con un perfil energético más diversificado, con menor proporción de CO₂ gracias a la energía nuclear.

  - Rusia ha mantenido una presencia relevante, especialmente en la era soviética y posterior (cómo republica), vinculada al uso intensivo de carbón, petróleo y gas.

  - Canadá, aunque no se ubica entre los máximos emisores, también figura de forma consistente, reflejando su papel como economía industrializada con alta dependencia de recursos fósiles. 

- **Comparación China vs USA (1925–2021)**  
  - Hasta mediados del siglo XX, EE.UU. fue el principal emisor global, con amplia ventaja sobre China.

  - Desde la década de 1970, China comenzó un crecimiento sostenido en sus emisiones, vinculado a su industrialización, urbanización y demanda energética.

  - En 2006, se produjo el punto de quiebre: China superó a EE.UU. en emisiones anuales, marcando un cambio estructural en la geografía de emisiones de carbón a nivel global.  

  - Mientras que las emisiones de EE.UU. tienden a estabilizarse e incluso descender levemente, China mantiene una trayectoria ascendente, reflejando también la transición del liderazgo económico y energético global hacia el continente asiatico.

- **Fuentes de emisiones**  
  - **Carbón (Coal)** ha sido históricamente la fuente más dominante, con un repunte acelerado a comienzos del año 2000.  
  - **Petróleo (Oil)** tuvo un crecimiento marcado desde mediados del siglo XX, aunque con algunas caídas en los 70 y 80.  
  - **Gas** muestra un crecimiento sostenido desde 1950, consolidándose como una fuente relevante en la transición energética.  
  - **Cement y Flaring** tienen un impacto comparativamente menor, aunque como fuente Cement, presenta un leve aumento desde la década de 1980.

---

### 📌 Síntesis
 - El peso de las emisiones globales pasó de un dominio inicial de EE.UU. en el siglo XX a un liderazgo actual de China en el XXI, lo que refleja también los cambios en la economía mundial.

 - Las fuentes fósiles tradicionales (carbón, petróleo y gas) siguen siendo protagonistas absolutas, evidenciando la persistente dependencia de estos recursos a pesar del avance de las energías renovables.

 - Los mayores incrementos en emisiones se asocian a periodos de industrialización, urbanización y expansión económica, mostrando la estrecha relación estructural entre desarrollo y emisiones.

 - En el escenario actual, se observa una estabilización relativa de las emisiones en economías desarrolladas (como EE.UU. y Europa) frente a un ascenso sostenido en países emergentes, especialmente China, lo que plantea desafíos globales en términos de equidad y responsabilidad compartida en la reducción de emisiones.

Estas conclusiones constituyen una base sólida para discutir **políticas energéticas, estrategias de mitigación y compromisos internacionales** frente al cambio climático, donde la cooperación entre países desarrollados y emergentes será clave para lograr una transición efectiva hacia una economía baja en carbono.

----

🧠**Nota técnica**: todos los cálculos y visualizaciones se realizaron en Python utilizando pandas, matplotlib y seaborn. Los datos provienen del Global Carbon Project (versión 27, año 2022).